// ==UserScript==
// @name         UHP Schedule CTT and Fill Rate
// @namespace    http://tampermonkey.net/
// @version      42.0
// @description  CTT, VNHE, fade, report, Slack with geo cluster API, kvdb cooldown, node owners
// @match        https://amazon.unifiedhiringportal.com/schedules*
// @grant        GM_getValue
// @grant        GM_setValue
// @run-at       document-start
// @updateURL    https://raw.githubusercontent.com/ctwhit/uhp-enhancer.user.js/main/uhp-enhancer.user.js
// @downloadURL  https://raw.githubusercontent.com/ctwhit/uhp-enhancer.user.js/main/uhp-enhancer.user.js
// ==/UserScript==
(function () {
 'use strict';
 var STORAGE_KEY = 'uhp_aqua_data_v12';
 var SLACK_WEBHOOK = 'https://hooks.slack.com/services/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';
 var KVDB = 'https://kvdb.io/GTfupUArU2g4pE6Lv9KNhM/lastSent';
 var COOLDOWN = 30 * 60 * 1000;
 var apiSchedules = [];
 var geoMap = {};
 var VNHE_SITES = new Set(['WFG1','WLC1','WNM3','WNM4','WNM6','WTX1','WTX3','WTX9','WNY4','WFB1','WGE2','QBM3','QKY9','QBM9','WBM3','WMG1','XAL2','HMB1','QFL3','QFL9','QMS2','WFL3','WML1','WMS2','XMS2','XMS4','QZZ8','WID1','WID3','WEE1','WMD2','WFK1','WSC6','WPT2','QOL1','WBV1','QOL9','WCO5','WCO8','WCO9','WOL1','WWY1','WMI1','WMI4','XSA2','SSC3','WSC2','WND2','WND3','WND6','WMT2','WMT3','WMT4','WMT5','WWG5','WMI2','QBY8','QMA9','WNC9','WTN1','WWV8','QES1','WNG1','QDE1','WDE1','QBR2','QVA3','WGR2','WGR3','WUT1','WKN5','XSF2','QBA4','QKS3','WGC8','WKS1','WKS3','WKS4','WMO7','XWI2','WKN3','XJO1','QBE1','WMD1','WPY1','DLL4','WIL1','WIL4','QMS4','WET1','WMS4','WMN6','WWI4','WWI6','WIO9','DFR7','WMN3','WMN4','WMN8','WLN3','WLN6','WIO2','WIO3','WNB2','WNB4','WOR1','WOR3','WPR1','WZN2','WZN4','QZN1','WZN1','WZN6','QAV9','WOO1','WWV9','WWS1','QTX5','WSD2','WTX4','WTX5','WVC1','QKY3','WIN1','WKY3','WKY5','XEV1','DHI2','WUT3','WUT4','QHS3','QIL5','QMO4','WIL3','WIL5','WMO3','WMO4','WMO6','WNY1','WNY3','QLP6','WFL6','QMS9','WFL4','WOR2','QFS1','WKS2','WCF7','WKN2','QTX9']);
 var NODE_OWNERS = {'BOS - North':'abrdavi','SWF':'abrdavi','ORF':'acjoness','RIC':'acjoness','IND':'ahampton','SDF':'ahampton','OKC':'brownamt','DAL - North':'butlerdt','MIA':'carbajes','MKE':'cdcarden','MLI':'cdcarden','EWR':'ceilen','RDG':'ceilen','SYR':'ceilen','LAX - South':'chariwan','BHM - North':'colleent','BHM - South':'colleent','BNA':'colleent','BOS - South':'dawwelli','ROC':'delmegem','ONT - North':'dmmiyamo','ATL - East':'domnant','SMF':'durice','PHX - North':'galfink','FWA':'hageeric','GRR':'hageeric','CLE':'hawvance','HOU':'henashly','CVG':'hpappas','MSP':'huzmha','ISP':'jaschmie','NYC':'jaschmie','ONT - South':'jerecf','PHX - South':'jerecf','MCO':'kaylacm','MSY':'knijaco','ALB':'kodjahli','JAX':'levych','ABQ':'lovarobe','GEG':'mackegra','DCA':'mbarbala','TPA':'mcgscott','LAS':'mickiep','MCI - North':'mkeel','MCI - South':'mkeel','BDL':'nbhusri','DTW - North':'ncolmil','DTW - South':'ncolmil','MDW - North':'osoteo','DEN':'pattedar','OMA':'pattedar','SAV':'pkkwiek','PVD':'ramokri','FAT':'rosusn','DSD':'rugabr','CMH':'rysawyer','AUS':'sauclaud','SAT':'sauclaud','DAL - South':'simopaul','PIT':'snatchch','PDX':'ssarisr','FSD':'stefbaw','LAX - North':'stthapar','STL':'swemich','MEM':'tammyale','BWI':'tanypace','MDT':'tanypace','CLT':'teagw','RDU':'teagw','OAK':'therevig','ILG':'thomatoj','PHL':'thomatoj','GSO':'timodwye','AGS':'tlarsona','ATL - West':'tlarsona','SLC':'tttanzi','BOI':'vandbenj','MDW - South':'yulewall','BFI':'zunmarta','SFO':'zunmarta'};
 var origXhrOpen = XMLHttpRequest.prototype.open; var origXhrSend = XMLHttpRequest.prototype.send;
 XMLHttpRequest.prototype.open = function (m, url) { this._url = url; return origXhrOpen.apply(this, arguments); };
 XMLHttpRequest.prototype.send = function () { this.addEventListener('load', function () { try { var j = JSON.parse(this.responseText); if (this._url && this._url.includes('schedule-entities') && j.data && Array.isArray(j.data)) { apiSchedules.length = 0; j.data.forEach(function (s) { apiSchedules.push(s); }); } if (this._url && this._url.includes('geo-clusters') && j.data && Array.isArray(j.data)) { j.data.forEach(function (g) { geoMap[g.geoClusterId] = {name:g.geoClusterName||'',region:g.region||'',zone:g.zone||''}; }); } } catch (_) {} }); return origXhrSend.apply(this, arguments); };
 var origFetch = window.fetch;
 window.fetch = function () { var a = arguments; var u = typeof a[0] === 'string' ? a[0] : (a[0] && a[0].url) || ''; return origFetch.apply(this, a).then(function (r) { if (u.includes('schedule-entities') || u.includes('geo-clusters')) { try { var c = r.clone(); c.json().then(function (j) { if (u.includes('schedule-entities') && j.data && Array.isArray(j.data)) { apiSchedules.length = 0; j.data.forEach(function (s) { apiSchedules.push(s); }); } if (u.includes('geo-clusters') && j.data && Array.isArray(j.data)) { j.data.forEach(function (g) { geoMap[g.geoClusterId] = {name:g.geoClusterName||'',region:g.region||'',zone:g.zone||''}; }); } }).catch(function () {}); } catch (_) {} } return r; }); };
 function getData() { try { return JSON.parse(GM_getValue(STORAGE_KEY, '{}')); } catch (_) { return {}; } }
 function formatDate(s) { if (!s || s === 'None' || s === 'none' || s === 'N/A') return ''; var c = s.replace(/\s+\d{1,2}:\d{2}(:\d{2})?\s*$/, '').trim(); var p = c.match(/(\d{4})[-/](\d{1,2})[-/](\d{1,2})/); if (p) return new Date(parseInt(p[1]), parseInt(p[2]) - 1, parseInt(p[3])).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); var p2 = c.match(/(\d{1,2})[-/](\d{1,2})[-/](\d{4})/); if (p2) return new Date(parseInt(p2[3]), parseInt(p2[1]) - 1, parseInt(p2[2])).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); return c; }
 function parseCSV(text) { var lines = text.split(/\r?\n/).filter(function (l) { return l.trim(); }); if (lines.length < 2) return {}; var headers = lines[0].split(',').map(function (h) { return h.trim().replace(/^"|"$/g, ''); }); var hl = headers.map(function (h) { return h.toLowerCase(); }); var idCol = hl.findIndex(function (h) { return h.includes('schedule') && h.includes('id'); }); var cttCol = hl.findIndex(function (h) { return h.includes('ctt'); }); if (idCol === -1 || cttCol === -1) return {}; var data = {}; for (var i = 1; i < lines.length; i++) { var cols = []; var cur = ''; var inQ = false; for (var j = 0; j < lines[i].length; j++) { var ch = lines[i][j]; if (ch === '"') { inQ = !inQ; continue; } if (ch === ',' && !inQ) { cols.push(cur.trim()); cur = ''; continue; } cur += ch; } cols.push(cur.trim()); var id = cols[idCol]; if (!id) continue; data[id] = { ctt: cols[cttCol] || '' }; } return data; }
 function getGeoInfo(geoId) { var g = geoMap[geoId]; if (!g) return {node:'',region:'',zone:''}; var z = g.zone || ''; var region = z.includes('East') ? 'East' : z.includes('West') ? 'West' : z; return {node:g.name,region:region,zone:g.region}; }
 function buildReportData() { var csv = getData(); var f = apiSchedules.filter(function (s) { var st = (s.aggregatedScheduleStatus||'').toLowerCase(); var r = (s.scheduleStatusReason||[]).map(function (x) { return x.toLowerCase(); }); return st.includes('unposted') && r.some(function (x) { return x.includes('nhe') && x.includes('unavailable'); }) && !r.some(function (x) { return x.includes('ctt') && x.includes('reached'); }); }); return f.map(function (s) { var site = (s.scheduleSiteId||'').replace('SITE-',''); var id = s.scheduleId||''; var info = csv[id]||{}; var gi = getGeoInfo(s.scheduleGeoClusterId); var role = s.scheduleRole||''; return {region:gi.region,zone:gi.zone,node:gi.node,site:site,id:id,ldAvailable:s.laborDemandAvailableCount!=null?s.laborDemandAvailableCount:'',ctt:formatDate(info.ctt),vnheSite:VNHE_SITES.has(site),lockerRole:role==='Locker+ Associate',vnhe:(VNHE_SITES.has(site)||role==='Locker+ Associate')?'Yes':'No'}; }).sort(function (a,b) { return (a.region+a.zone+a.node+a.site).localeCompare(b.region+b.zone+b.node+b.site); }); }
 function generateReport() { var rows = buildReportData(); if (!rows.length) { alert('No data'); return; } var h = 'Region,Zone,Node,Site,Schedule ID,LD Available,CTT Date,VNHE Site'; var c = rows.map(function (r) { return '"'+r.region+'","'+r.zone+'","'+r.node+'","'+r.site+'","'+r.id+'","'+r.ldAvailable+'","'+r.ctt+'","'+r.vnhe+'"'; }); var b = new Blob([h+'\n'+c.join('\n')],{type:'text/csv'}); var u = URL.createObjectURL(b); var a = document.createElement('a'); a.href = u; a.download = 'Unposted_NHE_Report_'+new Date().toISOString().split('T')[0]+'.csv'; a.click(); URL.revokeObjectURL(u); }
 function sendToSlack() {
   var rows = buildReportData();
   if (!rows.length) return;
   origFetch.call(window, KVDB + '?t=' + Date.now()).then(function (res) { return res.text(); }).then(function (val) {
     var last = parseInt(val) || 0;
     var diff = Date.now() - last;
     if (diff < COOLDOWN) { console.log('[UHP] Cooldown - '+Math.round((COOLDOWN-diff)/60000)+' min left'); return; }
     origFetch.call(window, KVDB, {method:'PUT',body:String(Date.now())});
     var date = new Date().toLocaleDateString('en-US',{month:'short',day:'numeric'});
     var time = new Date().toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'});
     var msg = ':clipboard: *Unposted NHE Unavailable Report — '+date+' '+time+'* ('+rows.length+' schedules)\n:thumbsup: React with thumbs up once reviewed\n\n';
     var lastZone = ''; var lastRegion = ''; var lastNode = '';
     for (var i = 0; i < rows.length; i++) {
       var r = rows[i];
       if (r.region !== lastZone) { msg += '\n*'+r.region.toUpperCase()+'*\n\n'; lastZone = r.region; lastRegion = ''; lastNode = ''; }
       if (r.zone !== lastRegion) { msg += '*'+r.zone+'*\n'; lastRegion = r.zone; lastNode = ''; }
       if (r.node !== lastNode) {
         var owner = NODE_OWNERS[r.node] || '';
         msg += '*' + r.node + (owner ? ' (@'+owner+')' : '') + '*\n';
         lastNode = r.node;
       }
       var tags = '';
       if (r.vnheSite) tags += ' *[VNHE]*';
       if (r.lockerRole) tags += ' *[Locker]*';
       msg += '  '+r.site+' - '+r.id+' | LD:'+r.ldAvailable+tags+'\n';
     }
     fetch(SLACK_WEBHOOK, {method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:msg})});
     console.log('[UHP] Slack sent at '+time);
   }).catch(function (e) { console.log('[UHP] KVDB error:',e); });
 }
 function injectDashboard() { if (location.pathname.includes('/Schedule/')) return; var data = getData(); var rows = document.querySelectorAll('tr'); for (var i = 0; i < rows.length; i++) { var row = rows[i]; if (row.querySelector('.aqua-badge')||row.querySelector('.vnhe-badge')) continue; var match = row.textContent.match(/SCH-[A-Z]+-\d+/); if (!match) continue; var cells = row.querySelectorAll('td'); if (!cells.length) continue; var isV = false; for (var j = 0; j < cells.length; j++) { var txt = cells[j].textContent.trim(); if (VNHE_SITES.has(txt)) isV = true; if (txt==='Locker+ Associate') isV = true; } if (isV) { var sc = cells[1]||cells[0]; var bv = document.createElement('span'); bv.className='vnhe-badge'; bv.textContent='VNHE'; bv.style.cssText='background:#ff4d4d;color:#fff;padding:2px 6px;border-radius:4px;font:bold 10px sans-serif;margin-left:4px;white-space:nowrap;display:inline-block;vertical-align:middle;'; sc.appendChild(bv); } var info = data[match[0]]; if (!info) continue; var ctt = formatDate(info.ctt); if (!ctt) continue; var target = cells[cells.length-1]; var b1 = document.createElement('span'); b1.className='aqua-badge'; b1.textContent='CTT: '+ctt; b1.style.cssText='background:#232f3e;color:#ff9900;padding:2px 8px;border-radius:4px;font:bold 11px sans-serif;margin-left:6px;white-space:nowrap;display:inline-block;vertical-align:middle;'; target.appendChild(b1); } }
 function fadeCttReached() { var rows = document.querySelectorAll('tr'); for (var i = 0; i < rows.length; i++) { var row = rows[i]; if (row.classList.contains('aqua-faded')) continue; if (row.textContent.includes('CTT date reached')) { row.classList.add('aqua-faded'); row.style.opacity='0.35'; } } }
 function showBanner() { var match = location.pathname.match(/\/schedules\/Schedule\/(SCH-[A-Z]+-\d+)/i); if (!match) return; if (document.getElementById('aqua-banner')) return; var info = getData()[match[1]]; if (!info) return; var ctt = formatDate(info.ctt); if (!ctt) return; var banner = document.createElement('div'); banner.id='aqua-banner'; banner.style.cssText='background:#232f3e;color:#fff;padding:12px 20px;font:bold 14px sans-serif;display:flex;gap:20px;align-items:center;position:sticky;top:0;z-index:999999;box-shadow:0 2px 8px rgba(0,0,0,.3);'; var s1 = document.createElement('span'); s1.textContent='CTT: '+ctt; s1.style.color='#ff9900'; banner.appendChild(s1); document.body.prepend(banner); }
 function addControls() { if (document.getElementById('aqua-controls')) return; var wrap = document.createElement('div'); wrap.id='aqua-controls'; wrap.style.cssText='position:fixed;bottom:10px;right:10px;z-index:999999;display:flex;gap:6px;align-items:center;'; var slackBtn = document.createElement('div'); slackBtn.style.cssText='background:#4A154B;color:#fff;padding:10px 16px;border-radius:8px;font:bold 13px sans-serif;cursor:pointer;box-shadow:0 2px 8px rgba(0,0,0,.3);'; slackBtn.textContent='Send to Slack'; slackBtn.addEventListener('click',sendToSlack); wrap.appendChild(slackBtn); var reportBtn = document.createElement('div'); reportBtn.style.cssText='background:#232f3e;color:#ff9900;padding:10px 16px;border-radius:8px;font:bold 13px sans-serif;cursor:pointer;box-shadow:0 2px 8px rgba(0,0,0,.3);'; reportBtn.textContent='Download Report'; reportBtn.addEventListener('click',generateReport); wrap.appendChild(reportBtn); var count = Object.keys(getData()).length; var btn = document.createElement('label'); btn.style.cssText='background:#232f3e;color:#ff9900;padding:10px 16px;border-radius:8px;font:bold 13px sans-serif;cursor:pointer;box-shadow:0 2px 8px rgba(0,0,0,.3);'; btn.textContent=count>0?'Aqua: '+count+' (update)':'Upload Aqua CSV'; var input = document.createElement('input'); input.type='file'; input.accept='.csv'; input.style.display='none'; input.addEventListener('change',function(e){ var file=e.target.files[0]; if(!file) return; var reader = new FileReader(); reader.onload=function(){ var d=parseCSV(reader.result); var c=Object.keys(d).length; if(c>0){GM_setValue(STORAGE_KEY,JSON.stringify(d)); btn.textContent='Loaded '+c; setTimeout(function(){location.reload();},500);} else{btn.textContent='No data';} }; reader.readAsText(file); input.value=''; }); btn.appendChild(input); wrap.appendChild(btn); document.body.appendChild(wrap); }
 var autoSendCheck = setInterval(function () { if (apiSchedules.length && Object.keys(geoMap).length > 0) { clearInterval(autoSendCheck); sendToSlack(); } }, 3000);
 var run = function () { showBanner(); injectDashboard(); fadeCttReached(); addControls(); };
 new MutationObserver(run).observe(document.documentElement, { childList: true, subtree: true });
})();
